config/routes.rb
Rails.application.routes.draw do

	devise_scope :user do
		#root 'users#index'
		root 'devise/registrations#new'
	end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
 	

 	resources :users, only: [:index, :show] do		 
 		resource :profile
 	end
 	resources :friendships, only: [:create, :update, :destroy]
 	resources :likes
 	resources :posts, only: [:index, :show, :create, :destroy] do 
 		resources :likes
 		resources :comments, only: [:new, :show, :create, :update, :destroy]
 	end


 	get 'newsfeed/:id', to:'users#newsfeed',  as: :newsfeed
      	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :author, class_name: 'User'

	validates_uniqueness_of :post_id
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name: "User"
	
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :post, uniqueness: {scope: :user}
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user, optional: true
	has_many :comments
	has_many :likes
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user, :inverse_of => :profile, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  after_create :build_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  validates :first_name, presence: true

  has_one :profile
  has_many :posts

  has_many :comments, foreign_key: :author_id, dependent: :destroy

  has_many :likes
  
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
  
  has_many :active_friends, -> {where(friendships: { accepted: true})}, through: :friendships, source: :friend
  has_many :received_friends, -> {where(friendships: { accepted: true})}, through: :received_friendships, source: :user
  
  has_many :pending_friends, -> {where(friendships: { accepted: false})}, through: :friendships, source: :friend
  has_many :requested_friends, -> {where(friendships: { accepted: false})}, through: :received_friendships, source: :user

  accepts_nested_attributes_for :profile, :allow_destroy => true
  
  def friends
  	active_friends | received_friends
  end

  def pending
  	pending_friends | requested_friends
  end

  def feed
  	posts
  end

  def build_profile
    Profile.create(user: self)
  end

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
  end

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?
  #before_action :set_user

  private

  #def set_user
  ##	@user = current_user
  #end

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birthday])
  end

  def after_sign_in_path_for(resource)
 	newsfeed_path(resource)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_action :authenticate_user!
	before_action :set_post


	def new
		@user = current_user
		@comment = @post.comments.build
		@comment.author_id = @user.id
		
		
	end



	def create
		
	
		#@comment = current_user.posts.comments.create(comment_params)
		@comment = @post.comments.build(comment_params)
		#@comment.post_id = @post.id
		@post = Post.find(params[:post_id])
		#@comment.author_id = current_user.id
		@comment.author_id = current_user.id
		@comment.post_id = @post.id
		
		@comment.save
		if @comment.save!
			redirect_to new_post_comment_path(@post)
		#redirect_to newsfeed_path(current_user)
	end
	end

	private

	def comment_params
		params.require(:comment).permit(
								:id, 
								:author_id,
								:post_id,
								:body)
	
	end

	def set_post
		@post = Post.find(params[:post_id])
	end
end




	

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
  
  

  def create
  	@user = current_user
  	@like = Like.new(like_params)
  	@like.user_id = current_user.id
  	if @like.save!
  		redirect_to newsfeed_path(@user)
  	end
  end

  def update
    @friendship = Friendship.find_by(id: params[:id])
    @friendship.update(status: true)
    if @friendship.save
      redirect_to newsfeed_path(current_user)
    end
  end


  private

  def like_params
  	params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_post, only: [:show, :index]

	#def new
	#	@user = current_user
	#	@post = @user.posts.build
	#	@comment = Comment.new(post_id: params[:post_id])
	#send

	def show
		@user = current_user
		@post = Post.find(params[:id])
		#@comment = Comment.new(:post => @post)
		#@comment.author_id = current_user.id
		#@comment.save
		#@comments = Comment.find_by(params[:post_id])
		redirect_to newsfeed_path(current_user)
	end

	def create
		@post = current_user.posts.build(post_params)
		
		
		if @post.save
		redirect_to newsfeed_path(current_user)
		end		

	end

	private
	
	def set_post
		@post = Post.find_by!(params[:id])
	end
	def post_params
		params.require(:post).permit(
								:id, 
								:user_id,
								:post_id,
								:title, 
								:body)
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def new
    #@user = current_user
    #@profile = Profile.new
    @profile = Profile.new
    
  end

  def edit
     @user = current_user
     @profile = Profile.find(params[:user_id])
  end

  def show
    @user = current_user
    @profile = Profile.find_by(params[:user_id])
  end

  def update
    @profile = Profile.find_by(params[:user_id])
    @profile.update(profile_params)
    @profile.save
    if @profile.save
      redirect_to user_profile_path(current_user)
    end

  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    @profile.save
    if @profile.save
      redirect_to newsfeed_path(current_user)
    end
  end

  def destroy
  end

  private 

  def profile_params
    params.require(:profile).permit(
                :id,
                :birthday,
                :hometown,
                :college,
                :words_to_live_by,
                :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

	def index
		@users = User.all
	end

	def newsfeed
		@post_new = current_user.posts.build
		@posts = current_user.posts
		@feed_items = current_user.feed

	end

	private


end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		"http://gravatar.com/avatar/#{gravatar_id}.png?"
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<%=form_for(current_user.posts.comments.build, remote: true) do |f| %>
	sdfsdf
	<%=f.text_area :body, placeholder: "Provide comment" %>
	<%=f.hidden_field_tag :post_id, post.id %>
	<%=f.hidden_field_tag :author_id, :value => current_user.id %> 

	<%=f.submit "Leave comment" %>

<%end %>

app/views/comments/new.html.erb
<%=link_to "newsfeed", newsfeed_path(current_user)%>
<%=@post.body %>


<%=simple_form_for(@post.comments.build, :url =>  post_comments_path(@post.id), :method => :create) do |f| %>
	
	<%=f.text_area :body, placeholder: "Provide comment" %>
	
	<%=f.hidden_field :author_id, :value => current_user.id %> 
	

	<%=f.submit "Leave comment" %>

<%end %>

<% if @post.comments.any? %>
	<%=@post.comments.each do |c| %>
	<%=c.body %>
	<%=c.author.inspect %>
	<%=@post.comments.count%>
	<%end %>
	<%end %>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/posts/_post.html.erb
<%= render template: 'posts/show', :locals => {:post => post} %>

app/views/posts/index.html.erb
<%=form_with(model: post, local: true) do |form| %>
	<%=form.text_field :title %>
	<%=form.text_field :body %>

	<%= form.submit("post") %>

<%end %>

app/views/posts/new.html.erb
<%=form_for(@post_new, remote: true) do |f| %>

	
	<%=f.text_area :body, :placeholder => "Whats on your mind?"%>


	<%=f.submit "Post" %>



<%end%>

app/views/posts/show.html.erb
<h2><%=post.title %></h2>

<p><%=post.body %></p>

<%unless post.body.nil? %>

	<%=form_for(current_user.likes.build) do |f| %>
	<%= f.hidden_field :post_id, value: post.id %>
	<%= f.submit "Like" %>
	<%end %>

	<% if post.likes.any? %>

	<%=post.likes.count%><p>(likes)</p>

	<%end %>





	<%=link_to "Comments", new_post_comment_path(post_id: post.id) %><br>
<% if post.comments.any? %>
	<%post.comments.each do |c| %>
	<%= c.body %>
	<%= c.author.email %>
	<%= c.created_at %>

	<%end %>
<%end%>

<%end %>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

<%=current_user.email %>

<%=simple_form_for([@user, @profile], :url => user_profile_path, :controller => :profiles, :action => :update) do |f| %>
	<%=f.input :birthday %>
	<%=f.input :college %>
	<%=f.input :words_to_live_by %>
	<%=f.input :hometown %>
	<%=f.button :submit %>
<%end%>

<%=link_to "back", user_profile_path(current_user) %>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>


<%=current_user.email %>

<%=simple_form_for([@user, @profile], :url => user_edit_profile_path, :controller => :profile, :action => :update) do |f| %>
	<%=f.input :birthday %>
	<%=f.input :college %>
	<%=f.input :words_to_live_by %>
	<%=f.input :hometown %>
	<%=f.button :submit %>
<%end%>

app/views/profiles/show.html.erb
<%= current_user.email %><br>


<h4>Birthday: <%=@profile.birthday %></h2><br>
<%=@profile.hometown %><br>
<%=@profile.college %><br>

<%=link_to "edit profile", edit_user_profile_path(current_user) %>
<%=link_to "back", newsfeed_path(current_user) %>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>

app/views/users/index.html.erb
<% if current_user.requested_friends.any? %>
<% current_user.requested_friends.each do |request| %>
		<%=request.email %>
		<%=link_to "Accept", friendships_update_path(id: request.id, method: "put") %>
		<%=link_to "Decline", friendships_destroy_path(id: request.id, method: :delete) %>
	<%end%>
	<%end%>

<h1>Users</h1>

<%@users.each do |u| %>
	<tr>
	
		<td><%=image_tag avatar_url(u) %></td>
		<td><%=u.email%>
			<% if u.id != current_user.id %>
		<%=link_to "Add friend", friendships_path(friend_id: u), method: :post %></td>
		<%end %><br>
	
	</tr>
	
	
<%end%>

app/views/users/newsfeed.html.erb
<%=current_user.pending.count %><p>pending friend request</p>

<% if current_user.requested_friends.any? %>
<% current_user.requested_friends.each do |request| %>
		<%=request.email %>
		<%=link_to "Accept", friendship_path(friend_id: request.id), :method => :put %>
		<%=link_to "Decline", friendships_path(friend_id: request.id, method: :delete) %><br>
	<%end%>
	<%end%>


<%=link_to "profile", edit_user_profile_path(current_user) %> 

user_
<%=link_to "view profile", user_profile_path(current_user)%>

<%=render template: 'posts/new'%>


<%= render 'shared/feed' %>

<%=link_to "users", users_path %>